from particula import particula

# p1 = particula()
# p1.set_valores([1,1,1],[1,1,1],[1,1,1])
# p2 = particula()
# p2.init_random()
# print(p1.distancia(p2))
# p3 = particula()
# p3.set_valores([2,2,2],[1,1,1],[1,1,1])
# print(p1.distancia(p3))
from particula import *
p1 = particula()
p2 = particula()
p3 = particula()
p2.set_valores(np.array([3.0,4.0,0.0]), np.zeros(3),np.zeros(3))
p3.init_random()
p1.muestra()
p2.muestra()
p3.muestra()
print ("distancia: ",p1.distancia(p2))
